# Licensed under MIT (https://github.com/ligoj/plugin-api/blob/master/LICENSE)
# Properties (not JSON/XML) on purpose:
# - JsonConfigurationFactory needs Jackson 2 (com.fasterxml.*), removed by the Jackson 3 migration.
# - XmlConfigurationFactory uses the JDK DOM parser, which triggers a LinkageError when Log4j
#   initializes inside Spring's SimpleThrowawayClassLoader (JPA temp classloader): that child-first
#   loader re-defines org.xml.sax.* from the jrt image (not in OverridingClassLoader's excluded
#   packages), clashing with java.xml's DocumentBuilder signature.
# The properties factory is parsed by Log4j itself with no external dependency.
status = warn
name = Main
monitorInterval = 60

property.filename = target/rolling.log

filter.threshold.type = ThresholdFilter
filter.threshold.level = debug

appender.console.type = Console
appender.console.name = STDOUT
appender.console.layout.type = PatternLayout
appender.console.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %msg%xEx{filters(com.sun.proxy,org.springframework.data.projection,org.springframework.dao.support,org.springframework.transaction,java.lang.Thread,org.apache.cxf,org.eclipse.jetty,org.springframework.web,javax.servlet,org.springframework.aop,org.junit,org.apache.maven,sun.reflect,java.lang.reflect,org.springframework.cglib,org.springframework.security)}%n

appender.verbose.type = Console
appender.verbose.name = STDOUT_VERBOSE
appender.verbose.layout.type = PatternLayout
appender.verbose.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n

appender.rolling.type = RollingFile
appender.rolling.name = RollingFile
appender.rolling.fileName = ${filename}
appender.rolling.filePattern = target/rolling.%i.log.gz
appender.rolling.layout.type = PatternLayout
appender.rolling.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
appender.rolling.policies.type = Policies
appender.rolling.policies.size.type = SizeBasedTriggeringPolicy
appender.rolling.policies.size.size = 500

logger.filterchain.name = org.springframework.security.web.FilterChainProxy
logger.filterchain.level = info
logger.filterchain.additivity = false
logger.filterchain.appenderRef.stdout.ref = STDOUT

logger.sql.name = org.hibernate.SQL
logger.sql.level = debug
logger.sql.additivity = false
logger.sql.appenderRef.stdout.ref = STDOUT

logger.cxfphase.name = org.apache.cxf.phase.PhaseInterceptorChain
logger.cxfphase.level = error
logger.cxfphase.additivity = false
logger.cxfphase.appenderRef.stdout.ref = STDOUT

logger.hibpersistence.name = org.hibernate.ejb.HibernatePersistence
logger.hibpersistence.level = error
logger.hibpersistence.additivity = false
logger.hibpersistence.appenderRef.stdout.ref = STDOUT

logger.ldapattr.name = org.apache.directory.server.schema.registries.DefaultAttributeTypeRegistry
logger.ldapattr.level = fatal
logger.ldapattr.additivity = false
logger.ldapattr.appenderRef.stdout.ref = STDOUT

logger.ldapdir.name = org.apache.directory.server.core.DefaultDirectoryService
logger.ldapdir.level = error
logger.ldapdir.additivity = false
logger.ldapdir.appenderRef.stdout.ref = STDOUT

logger.ldif.name = org.apache.directory.server.protocol.shared.store.LdifFileLoader
logger.ldif.level = warn
logger.ldif.additivity = false
logger.ldif.appenderRef.stdout.ref = STDOUT

logger.ldaptemplate.name = org.springframework.ldap.core.LdapTemplate
logger.ldaptemplate.level = warn
logger.ldaptemplate.additivity = false
logger.ldaptemplate.appenderRef.stdout.ref = STDOUT

rootLogger.level = info
rootLogger.appenderRef.stdout.ref = STDOUT
